"""first

Revision ID: 0b35a090a878
Revises: dee91b277e0f
Create Date: 2022-04-01 15:14:20.845683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b35a090a878'
down_revision = 'dee91b277e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
